language: python
python:
  - "2.7"

addons:
  sauce_connect: true

before_install:
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWZpZHVz`
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9OWU5ZGJkNzctNDIwOC00ODM5LTkwY2ItMTZkM2M5ODUxZGMw`
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg-dev python-dev python-virtualenv gettext zlib1g-dev git

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install flake8
  - pip install selenium

script:
  - flake8
  - coverage run manage.py init
  - coverage run manage.py test

after_success:
  - coverage report
  - coveralls
