language: python
python:
  - "3.6"
node_js:
  - "10"

dist: trusty
sudo: required

addons:
  chrome: stable

install:
  - mv travis/configuration.py ./
  - pip3 install requests[security]
  - pip3 install -r requirements.txt
  - pip3 install -r dev-requirements.txt
  - flake8 ./
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install selenium
  - pip3 install chromedriver
  - coverage run manage.py init --no-static --no-compress
  - ./manage.py check_js

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TESTS=user
    - TESTS=document

script: travis_retry coverage run manage.py test $TESTS

jobs:
  include:
    - stage: coveralls
      addons: {}
      before_cache: skip
      cache: false
      before_install: skip
      install: skip
      after_success: skip
      env: TESTS=done
      before_script: x="bas";`"$x"e64 -d <<< ZXhwb3J0IENPVkVSQUxMU19SRVBPX1RPS0VOPUlJOERBY284cU00bTZXemlHTXFjdlNTQ05vclFMVmgxTg==`
      script: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$TRAVIS_BUILD_NUMBER&payload[status]=done"

after_success:
  - coverage report
  - coveralls

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - static-libs
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
