language: python
python:
  - "3.8"
node_js:
  - "12"

dist: bionic
sudo: required

addons:
  chrome: stable

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

install:
  - cd fiduswriter
  - mv ../travis/configuration.py ./
  - pip3 install requests[security]
  - pip3 install -r requirements.txt
  - pip3 install -r dev-requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
  - coverage run manage.py setup --no-static

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST='browser_check base'
    - TEST=user
    - TEST=feedback
    - TEST=document.tests.test_collaboration
    - TEST=document.tests.test_editor
    - TEST=document.tests.test_offline
    - TEST=document.tests.test_export
    - TEST=document.tests.test_admin
    - TEST=document.tests.test_message_exchange
    - TEST=bibliography
    - TEST=usermedia

script:
    - travis_retry coverage run --concurrency=multiprocessing manage.py test $TEST

stages:
  - lint
  - test
  - coveralls

jobs:
  include:
    - stage: lint
      addons: {}
      before_install: cd fiduswriter
      install:
        - pip3 install -r requirements.txt
        - pip3 install coverage coveralls flake8==3.7.9
      env:
        - TESTS=before
        - COVERALLS_PARALLEL=true
      before_script: skip
      script: coverage run --concurrency=multiprocessing manage.py lint
    - stage: coveralls
      addons: {}
      before_cache: skip
      cache: false
      before_install: skip
      install: skip
      after_success: skip
      env: TESTS=done
      before_script: x="bas";`"$x"e64 -d <<< ZXhwb3J0IENPVkVSQUxMU19SRVBPX1RPS0VOPUlJOERBY284cU00bTZXemlHTXFjdlNTQ05vclFMVmgxTg==`
      script: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$TRAVIS_BUILD_NUMBER&payload[status]=done"

after_success:
  - coverage combine
  - coverage report
  - coveralls

cache:
  directories:
    - fiduswriter/.transpile
    - $HOME/.cache/pip
    - static-libs
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
