language: python
python:
  - "2.7"

sudo: required
dist: trusty

before_install:
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWZpZHVz`
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9OWU5ZGJkNzctNDIwOC00ODM5LTkwY2ItMTZkM2M5ODUxZGMw`
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg-dev python-dev gettext zlib1g-dev git npm

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install selenium
  - pip install sauceclient
  - npm install jshint@2.9.2
  - ./travis/sauce-connect.sh

script:
  - flake8 ./
  - ./node_modules/.bin/jshint .
  - coverage run manage.py init
  - coverage run manage.py test

after_success:
  - coverage report
  - coveralls
